In [9]:
import numpy as np

a = np.random.randn(5) ## don't use this
print(a)

[-1.08008199  0.94321055 -0.01664575  1.75258399 -0.1731389 ]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 0.92792882  1.00183389  0.28284452  1.35715086  1.37834039]


In [5]:
print(np.dot(a,a.T))

5.68640475745


In [10]:
a = np.random.randn(5,1) ## this is better!!!
print(a)

[[ 1.16873199]
 [-1.35006766]
 [-0.1124087 ]
 [ 0.20515883]
 [ 1.1826281 ]]


In [8]:
print(a.T)

[[ 0.77781082  0.106544   -0.85340872  2.01529843 -0.13500452]]


In [11]:
assert(a.shape == (5,1))